import { fileURLToPath } from 'node:url'
import { searchOptions } from '../docs/.vitepress/search.js'
import utilityMarkdown from '../docs/.vitepress/plugins/utility.js'
import {
  discoverUtilities,
  type Utility,
} from '../docs/.vitepress/utilities.js'
import { utilityTagGroups } from '../docs/.vitepress/tags.js'

/**
 * VitePress' local search reads each page's markdown from disk. Every utility
 * and tag page is a dynamic route with no file behind it, and its body is
 * generated by the `MarkdownTransform` plugin — so without the `_render` hook
 * in `search.ts` the indexer sees an empty string and the search box finds
 * nothing but the hand-written pages.
 */

// a renderer that hands the markdown back, so these assertions are about what
// gets indexed, not about how markdown-it renders it
const md = {
  renderAsync: async (src: string) => src,
} as unknown as Parameters<NonNullable<typeof searchOptions._render>>[2]

const render = (relativePath: string, src = '') =>
  searchOptions._render!(src, { relativePath } as any, md)

let utilities: Utility[]

beforeAll(async () => {
  utilities = await discoverUtilities()
}, 120_000)

describe('search index content', () => {
  it('has utilities to index', () => {
    expect(utilities.length).toBeGreaterThan(50)
  })

  it('indexes every utility page with its name and description', async () => {
    const empty: string[] = []

    for (const utility of utilities) {
      const indexed = await render(utility.pathMd.slice(1))

      if (!indexed.includes(utility.title) || indexed.length < 50) {
        empty.push(utility.pathMd)
      }
    }

    expect(empty).toEqual([])
    // one render per page, slow enough under coverage to need the room
  }, 60_000)

  it('indexes a utility page with prose the raw file does not contain', async () => {
    const utility = utilities.find((x) => x.description.length > 50)!
    const indexed = await render(utility.pathMd.slice(1))

    expect(indexed).toContain(utility.description.slice(0, 50))
  })

  it('drops twoslash from the indexed code blocks', async () => {
    const withExample = utilities.find((x) => x.examples?.length)!
    const indexed = await render(withExample.pathMd.slice(1))

    expect(indexed).toContain('```ts')
    expect(indexed).not.toContain('twoslash')
  })

  it('indexes every tag page with its description', async () => {
    const tags = utilityTagGroups.flatMap((group) => group.tags)

    for (const tag of tags) {
      const indexed = await render(`tags/${tag.name}.md`)

      expect(indexed, tag.name).toContain(tag.description)
    }
  })

  it('leaves a hand-written page to the default rendering', async () => {
    const src = '# Why\n\nbecause.'

    expect(await render('why.md', src)).toBe(src)
  })

  it('skips a page opting out via frontmatter', async () => {
    const skipped = await searchOptions._render!(
      '# Nope',
      { relativePath: 'why.md', frontmatter: { search: false } } as any,
      md,
    )

    expect(skipped).toBe('')
  })

  it('keeps the meta grid a component, not markup', async () => {
    const utility = utilities[0]
    const page = utilityMarkdown(utility, utilities)

    // The detailed view mounts the page without the theme's globally
    // registered components to build its excerpt. Written out as plain HTML,
    // the grid would push the description out of every excerpt.
    expect(page).toContain('<UtilityMeta ')
    expect(page).not.toContain('Source Code</a>')
    expect(await render(utility.pathMd.slice(1))).not.toContain('UtilityMeta')
  })
})

describe('search sections', () => {
  const split = (file: string, html: string) =>
    searchOptions.miniSearch!._splitIntoSections!(file, html) as Promise<
      { anchor: string; titles: string[]; text: string }[] | undefined
    >

  const pageFile = (relativePath: string) =>
    fileURLToPath(new URL(`../docs/${relativePath}`, import.meta.url))

  it('indexes a utility page as one section, anchored at its heading', async () => {
    const utility = utilities.find((x) => x.category === 'utils')!
    const html = `<h1 id="x"><a href="#${utility.slug}">${utility.title}</a></h1><p>prose</p>`

    // the anchor is what the detailed view keys a hit's excerpt by — without
    // it, a result shows its name and nothing else
    await expect(split(pageFile(utility.pathMd), html)).resolves.toEqual([
      {
        anchor: utility.slug,
        titles: [utility.title],
        text: `${utility.title}prose`,
      },
    ])
  })

  it('leaves a hand-written page to the default heading split', async () => {
    await expect(
      split(pageFile('why.md'), '<h1 id="why"><a href="#why">Why</a></h1>'),
    ).resolves.toBeUndefined()
  })
})

describe('search tokenizer', () => {
  const tokenize = searchOptions.miniSearch!.options!.tokenize as (
    text: string,
  ) => string[]

  it('makes the words inside a camelCase name searchable', () => {
    expect(tokenize('stringifyParams')).toEqual([
      'stringifyParams',
      'stringify',
      'Params',
    ])
  })

  it('splits an acronym off the word that follows it', () => {
    expect(tokenize('JSONQuery')).toEqual(['JSONQuery', 'JSON', 'Query'])
  })

  it('still splits on whitespace and punctuation', () => {
    expect(tokenize('one, two.three')).toEqual(['one', 'two', 'three'])
  })

  it('leaves a plain word alone', () => {
    expect(tokenize('cache')).toEqual(['cache'])
  })
})
